apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-secrets
  namespace: tech-challenge-system
type: Opaque
data: # do not use this values in production
  db_user: cG9zdGdyZXM= # base64 encoded value of "postgres"
  db_password: cG9zdGdyZXM= # base64 encoded value of "postgres"

# In production, you should use a secret management tool like HashiCorp Vault or AWS Secrets Manager
