apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-secrets
  namespace: tech-challenge-ns
type: Opaque
data: # do not use this values in production
  db_user: cG9zdGdyZXM= # base64 encoded value of "postgres"
  db_password: cG9zdGdyZXM= # base64 encoded value of "postgres"
  db_dsn: "aG9zdD1wb3N0Z3JlcyBwb3J0PTU0MzIgdXNlcj1wb3N0Z3JlcyBwYXNzd29yZD1wb3N0Z3JlcyBkYm5hbWU9dGVjaC1jaGFsbGVuZ2Ugc3NsbW9kZT1kaXNhYmxl" # base64 encoded value of "host=postgres..."

# In production, you should use a secret management tool like HashiCorp Vault or AWS Secrets Manager
