apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: tech-challenge-system
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP