# Test with HTTP Rest extension for VS Code 
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# @baseUrl = http://localhost:8080
@baseUrl = http://localhost
@num = 6
@name = John Doe {{num}}
@email = john.doe.{{num}}@email.com
@cpf = 123.456.789-0{{num}}
@customerId = 1

# @name getOrders

GET {{baseUrl}}/api/v1/orders HTTP/1.1

###

# @name getOrdersSorted

GET {{baseUrl}}/api/v1/orders?sort=customer_id HTTP/1.1

###

# @name getOrdersSortedDesc

GET {{baseUrl}}/api/v1/orders?sort=customer_id:d HTTP/1.1

###

# @name getOrdersSortedTwoFields

GET {{baseUrl}}/api/v1/orders?sort=customer_id:d,created_at HTTP/1.1

###

# @name getOrdersByStatus

GET {{baseUrl}}/api/v1/orders?status=OPEN HTTP/1.1

###

# @name getOrdersByStatuses

GET {{baseUrl}}/api/v1/orders?status=OPEN,RECEIVED HTTP/1.1

###

# @name getOrdersByStatusesExclude

GET {{baseUrl}}/api/v1/orders?status_exclude=OPEN,RECEIVED,PENDING,READY,PREPARING HTTP/1.1

###

# @name getOrdersByStatusesExcludeTrim

GET {{baseUrl}}/api/v1/orders?status_exclude=OPEN, RECEIVED,PENDING, READY ,PREPARING HTTP/1.1

### 

# @name getOrdersByStatusesExcludeNone

GET {{baseUrl}}/api/v1/orders?status_exclude=NONE HTTP/1.1
